name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Set up Android SDK
      uses: reactivecircus/android-sdk@v3
      with:
        api-levels: '30'
        target-sdk: '30'

    - name: Build APK
      run: ./gradlew assembleDebug
