name: Build APK

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        mkdir -p $HOME/Android/Sdk
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O android-sdk.zip
        unzip android-sdk.zip -d $HOME/Android/Sdk
        mkdir -p $HOME/Android/Sdk/cmdline-tools/latest
        mv $HOME/Android/Sdk/cmdline-tools/* $HOME/Android/Sdk/cmdline-tools/latest/
        echo 'export ANDROID_HOME=$HOME/Android/Sdk' >> $GITHUB_ENV
        echo 'export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin' >> $GITHUB_ENV
        source $GITHUB_ENV
        sdkmanager --update
        sdkmanager "platforms;android-30" "build-tools;30.0.3"

    - name: Build APK
      run: ./gradlew assembleDebug
